# Generated by Django 4.1 on 2022-08-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
